apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.strategy.canary.canaryService | default (printf "%s-canary" (include "knowledge-ai-frontend.fullname" .)) }}

  labels:
    {{- include "knowledge-ai-frontend.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http